### PR TITLE
AzureRM Provider v4 upgrade

### PR DESCRIPTION
**Pull request by zioproto**
## Description

Upgrades the module to the AzureRM provider V4

Replaces PR #82 

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates.
  - [X] Breaking changes.
  - [ ] Update to documentation

# Checklist

- [ ] I'm sure there are no other open Pull Requests for the same update/change
- [X] My corresponding pipelines / checks run clean and green without any errors or warnings
- [X] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by zioproto** [comment]
External PR:
* https://github.com/Azure/terraform-azurerm-avm-ptn-aks-production/pull/137

is blocked by this PR.

**Comment by kewalaka** [comment]
I realise there may be some urgency here - but skipping e2e tests is not good 😿

image

**Comment by zioproto** [comment]
@pradorodriguez could you please open a PR for the release notes, so we can use that PR to run the e2e tests that are missing in this PR ? Thanks

**Comment by tobiasehlert** [comment]
@Akashc0807, can you look into getting a new release of this module out?
Would be really appreciated so that others can merge theirs, like https://github.com/Azure/terraform-azurerm-avm-ptn-aks-production/pull/137

**Pull request merged**
